### ISSUE TITLE
The names of the styles in the dataset

### ISSUE THREAD

**Issue by ludandandan** [kwanyun/StyleSketch#5]
[ani_sketch_MJ, Disney_sketch_MJ, sketch_MJ, Rough_sketch_MJ, HIBLI_sketch_MJ, pencil_sj, low_sj] correspond to which styles in the dataset?

**Comment by kwanyun** [comment]
Yes, they correspond

**Comment by ludandandan** [comment]
Sorry, what I want to ask is which one of [ani_sketch_MJ, Disney_sketch_MJ, sketch_MJ, Rough_sketch_MJ, HIBLI_sketch_MJ, pencil_sj, low_sj] does style1 in the dataset correspond to, which one does style2 correspond to, and which ones do style3, style4, style5, style6 and style7 correspond to respectively?

**Comment by kwanyun** [comment]
Oh I forgot to mention it.

style1: ani_sketch
style2: low
style3: Disney_sketch
style4: GHIBLI_sketch
style5: sketch
style6: pencil
style7: Rough_sketch

**Comment by ludandandan** [comment]
Thank you so much
